//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_News
    {
        public int ID { get; set; }
        public System.Guid GUID { get; set; }
        public int CategoryID { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string ContentNews { get; set; }
        public string Authors { get; set; }
        public string Tags { get; set; }
        public Nullable<int> TotalView { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual cms_Categories cms_Categories { get; set; }
    }
}
