//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PortalEntities : DbContext
    {
        public PortalEntities()
            : base("name=PortalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<cms_Categories> cms_Categories { get; set; }
        public virtual DbSet<cms_News> cms_News { get; set; }
        public virtual DbSet<product_Categories> product_Categories { get; set; }
        public virtual DbSet<product_OrderDetails> product_OrderDetails { get; set; }
        public virtual DbSet<product_Orders> product_Orders { get; set; }
        public virtual DbSet<product_Products> product_Products { get; set; }
        public virtual DbSet<share_Images> share_Images { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
