//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    
    public partial class product_Products
    {
        public product_Products()
        {
            this.share_Images = new HashSet<share_Images>();
            this.product_OrderDetails = new HashSet<product_OrderDetails>();
        }
    
        public int ID { get; set; }
        public System.Guid GUID { get; set; }
        public string ProductCode { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Title { get; set; }
        public Nullable<int> Quantity { get; set; }
        public int Unit { get; set; }
        public decimal PriceOfUnit { get; set; }
        public Nullable<int> CoverImageID { get; set; }
        public string Description { get; set; }
        [AllowHtml]
        public string Description2 { get; set; }
        public Nullable<int> TotalView { get; set; }
        public Nullable<int> TotalBuy { get; set; }
        public string Tags { get; set; }
        public Nullable<bool> IsNewProduct { get; set; }
        public Nullable<bool> IsBestSellProduct { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual product_Categories product_Categories { get; set; }
        public virtual ICollection<share_Images> share_Images { get; set; }
        public virtual ICollection<product_OrderDetails> product_OrderDetails { get; set; }
    }
}
