//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class product_Categories
    {
        public product_Categories()
        {
            this.product_Products = new HashSet<product_Products>();
        }
    
        public int ID { get; set; }
        public System.Guid GUID { get; set; }
         [Display(Name = "Danh mục cha")]
        public System.Guid ParentID { get; set; }
         [Display(Name = "Tên danh mục")]
        public string Title { get; set; }
         [Display(Name = "Mô tả")]
        public string Description { get; set; }
         [Display(Name = "Đường dẫn")]
        public string Url { get; set; }
         [Display(Name = "Mức độ ưu tiên")]
        public Nullable<int> SortOrder { get; set; }
         [Display(Name = "Trạng thái")]
        public Nullable<int> Status { get; set; }
         [Display(Name = "Người tạo")]
        public Nullable<int> CreatedBy { get; set; }
         [Display(Name = "Ngày tạo")]
        public Nullable<System.DateTime> CreatedDate { get; set; }
         [Display(Name = "Người sửa")]
        public Nullable<int> ModifiedBy { get; set; }
         [Display(Name = "Ngày sửa")]
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<product_Products> product_Products { get; set; }
    }
}
