//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class product_Products
    {
        public product_Products()
        {
            this.share_Images = new HashSet<share_Images>();
            this.product_OrderDetails = new HashSet<product_OrderDetails>();
        }
    
        public int ID { get; set; }
        public System.Guid GUID { get; set; }
        [Display(Name = "Mã sản phẩm")]
        public string ProductCode { get; set; }
         [Display(Name = "Danh mục")]
        public Nullable<int> CategoryID { get; set; }
         [Display(Name = "Tên sản phẩm")]
        public string Title { get; set; }
         [Display(Name = "Số lượng")]
        public Nullable<int> Quantity { get; set; }
         [Display(Name = "Đơn vị")]
        public int Unit { get; set; }
         [Display(Name = "Giá")]
        public decimal PriceOfUnit { get; set; }
         [Display(Name = "Hình đại diện")]
        public Nullable<int> CoverImageID { get; set; }
         [Display(Name = "Mô tả")]
        public string Description { get; set; }
         [Display(Name = "Mô tả chi tiết")]
        [AllowHtml]
        public string Description2 { get; set; }
         [Display(Name = "Số lượt xem")]
        public Nullable<int> TotalView { get; set; }
         [Display(Name = "Số lượt mua")]
        public Nullable<int> TotalBuy { get; set; }
         [Display(Name = "Tags")]
        public string Tags { get; set; }
         [Display(Name = "Sản phẩm mới")]
        public Nullable<bool> IsNewProduct { get; set; }
         [Display(Name = "Sản phẩm bán chạy nhất")]
        public Nullable<bool> IsBestSellProduct { get; set; }
         [Display(Name = "Ưu tiên sắp xếp")]
        public Nullable<int> SortOrder { get; set; }
         [Display(Name = "Trạng thái")]
        public Nullable<int> Status { get; set; }
         [Display(Name = "Người tạo")]
        public Nullable<int> CreatedBy { get; set; }
         [Display(Name = "Ngày tạo")]
        public Nullable<System.DateTime> CreatedDate { get; set; }
         [Display(Name = "Người chỉnh sửa")]
        public Nullable<int> ModifiedBy { get; set; }
         [Display(Name = "Ngày chỉnh sửa")]
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual product_Categories product_Categories { get; set; }
        public virtual ICollection<share_Images> share_Images { get; set; }
        public virtual ICollection<product_OrderDetails> product_OrderDetails { get; set; }
    }
}
