//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_Orders
    {
        public product_Orders()
        {
            this.product_OrderDetails = new HashSet<product_OrderDetails>();
        }
    
        public int ID { get; set; }
        public System.Guid GUID { get; set; }
        public string UserID { get; set; }
        public string OrderCode { get; set; }
        public decimal TotalPrice { get; set; }
        public decimal FeeShip { get; set; }
        public decimal TotalOrder { get; set; }
        public int OrderStatus { get; set; }
        public string OrderNote { get; set; }
        public string NameOfRecipient { get; set; }
        public string PhoneOfRecipient { get; set; }
        public string AddressOfRecipient { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<product_OrderDetails> product_OrderDetails { get; set; }
    }
}
